baseurl: "https://tiendatecnica.netlify.app"
languageCode: "es"
title:  ' '
theme: "PaperMod"
menu:

  main:

    - identifier: Inicio
      name: Inicio
      url: /inicio/
      weight: 10

    - identifier: Contact us
      name: Contact√©nos
      url: /contacto/
      weight: 30

    - identifier: Catalogo
      name: Catalogo
      url: /catalogo/
      weight: 20
